### ISSUE TITLE
float TOC for pkgdown website

### ISSUE THREAD

**Issue by elong0527** [Merck/pkglite#16]
It seems pkgdown website allow float TOC. But our template did not enable it. 

https://pkgdown.r-lib.org/articles/pkgdown.html

**Comment by nanxstats** [comment]
Fixed by https://github.com/Merck/pkglite/commit/4a233dfdd25af9a101ff44318c3d3d6ba3705b43.

The patch uses a proper mechanism for style customization. It only keeps the differentiated style changes [using pkgdown/extra.css](https://pkgdown.r-lib.org/reference/init_site.html#custom-css-js), instead of replacing the original pkgdown.css entirely (which has the floating TOC stuff and can evolve from pkgdown updates).

I will send a PR to all the affected repos.
